language: java

jdk:
 - oraclejdk8

install:
 - mvn install -Dmaven.javadoc.skip=true -Dsource.skip=true -DskipTests=true -Dgpg.skip=true

script:
 - mvn clean compile test -Dgpg.skip=true

notifications:
  email: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2